### ISSUE TITLE
Back end does not provide enough information for editing the profiles

### ISSUE THREAD

**Issue by shighetari** [Lambda-School-Labs/Labs27-A-Ecosoap-BE#9]
https://github.com/Lambda-School-Labs/Labs27-A-Ecosoap-BE/blob/aba613b7009829af55c30c092e8f847deb8917a2/api/profile/profileServices.js#L1-L43

The back-end does not provide enough data to the front end to utilize the required CRUD operations. 
Back end should provide more additional information such as names and addresses for users.

**Should return :**
- ID
- contact name
- email address 
- organization 
- organization website
- contact phone
- contact email
- address
- Country
 
**Related issues:**
_Back end does not provide enough information for editing the profiles_
https://github.com/Lambda-School-Labs/Labs27-A-Ecosoap-FE/issues/7

**Comment by wSedlacek** [comment]
Added endpoint for `/me`
When logged in as a buyer it should provide all the information you need.
Admins do not have this information so you won't be able to get this info when logged in as an admin.
